// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenCodex.Data;

#nullable disable

namespace OpenCodex.Data.Migrations.SqliteMigrations
{
    [DbContext(typeof(OpenCodexSqliteDbContext))]
    [Migration("20260624072444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("OpenCodex.Core.Domain.AccessApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPlaintext")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastUsedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Id");

                    b.ToTable("AccessApiKeys", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompatJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Position");

                    b.HasIndex("OwnerUserId", "Priority", "Position");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CachedInputPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InputPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OutputPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("MatchPattern");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.HasIndex("Vendor");

                    b.ToTable("ModelPricings", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CompletedAt")
                        .HasColumnType("REAL");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<double?>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStream")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentRequestLogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProcessingStartedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TtftMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamModel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LifecycleStatus");

                    b.HasIndex("Model");

                    b.HasIndex("ParentRequestLogId");

                    b.HasIndex("Path");

                    b.HasIndex("RequestType");

                    b.HasIndex("StatusCode");

                    b.HasIndex("UpstreamModel");

                    b.HasIndex("OwnerUserId", "Id");

                    b.ToTable("RequestLogs", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLogDetail", b =>
                {
                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("OcrJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamTimingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamRequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSearchJson")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestLogId");

                    b.ToTable("RequestLogDetails", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLogStreamLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("OccurredAt")
                        .HasColumnType("REAL");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RequestLogId", "Sequence")
                        .IsUnique();

                    b.ToTable("RequestLogStreamLines", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.TavilyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.ToTable("TavilyKeys", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.WebSearchSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyUsageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WebSearchSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
