// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenCodex.Data;

#nullable disable

namespace OpenCodex.Data.Migrations.SqliteMigrations
{
    [DbContext(typeof(OpenCodexSqliteDbContext))]
    partial class OpenCodexSqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("OpenCodex.Core.Domain.AccessApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPlaintext")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastUsedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Id");

                    b.ToTable("AccessApiKeys", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircuitBreakDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompatJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Position");

                    b.HasIndex("OwnerUserId", "Priority", "Position");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ChannelModelInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("UpstreamModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("MatchPattern");

                    b.HasIndex("MatchType");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ChannelId", "UpstreamModel")
                        .IsUnique();

                    b.ToTable("ChannelModelInfos", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ChannelModelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("UpstreamModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("ChannelId", "Position");

                    b.HasIndex("ChannelId", "RequestModel");

                    b.ToTable("ChannelModelMappings", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.LogContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Compression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("RawLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoredLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("LogContentBlocks", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.LogContentManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RawLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("LogContentManifests", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.LogContentManifestChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("ManifestId", "Ordinal")
                        .IsUnique();

                    b.ToTable("LogContentManifestChunks", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Enabled");

                    b.HasIndex("MatchPattern");

                    b.HasIndex("MatchType");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Scope", "ChannelId", "ModelKey");

                    b.HasIndex("Scope", "ProviderId", "ModelKey");

                    b.ToTable("ModelInfos", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelPricingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChannelModelInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModelInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ChannelModelInfoId");

                    b.HasIndex("Enabled");

                    b.HasIndex("ModelInfoId");

                    b.ToTable("ModelPricingPlans", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelPricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TiersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillingItem");

                    b.HasIndex("Enabled");

                    b.HasIndex("PricingPlanId");

                    b.ToTable("ModelPricingRules", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Enabled");

                    b.HasIndex("SortOrder");

                    b.ToTable("ModelProviders", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CompletedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("ConversationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationTurnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationWindowId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStream")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentRequestLogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousResponseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PricingModelInfoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PricingPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProcessingStartedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TtftMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamModel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ConversationKey");

                    b.HasIndex("ConversationTurnId");

                    b.HasIndex("ConversationWindowId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LifecycleStatus");

                    b.HasIndex("Model");

                    b.HasIndex("ParentRequestLogId");

                    b.HasIndex("Path");

                    b.HasIndex("PreviousResponseId");

                    b.HasIndex("PricingModelInfoId");

                    b.HasIndex("PricingPlanId");

                    b.HasIndex("RequestType");

                    b.HasIndex("StatusCode");

                    b.HasIndex("UpstreamModel");

                    b.HasIndex("OwnerUserId", "Id");

                    b.ToTable("RequestLogs", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLogContentRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("TEXT");

                    b.Property<short>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.HasIndex("RequestLogId", "Slot")
                        .IsUnique();

                    b.ToTable("RequestLogContentRefs", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.TavilyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.ToTable("TavilyKeys", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.WebSearchSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<int>("KeyUsageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WebSearchSettings", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.LogContentManifestChunk", b =>
                {
                    b.HasOne("OpenCodex.Core.Domain.LogContentBlock", null)
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenCodex.Core.Domain.LogContentManifest", null)
                        .WithMany()
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLogContentRef", b =>
                {
                    b.HasOne("OpenCodex.Core.Domain.LogContentManifest", null)
                        .WithMany()
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenCodex.Core.Domain.RequestLog", null)
                        .WithMany()
                        .HasForeignKey("RequestLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
