// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenCodex.Data;

#nullable disable

namespace OpenCodex.Data.Migrations.PostgresMigrations
{
    [DbContext(typeof(OpenCodexPostgresDbContext))]
    [Migration("20260627143941_ModelCatalog")]
    partial class ModelCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenCodex.Core.Domain.AccessApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPlaintext")
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("LastUsedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Id");

                    b.ToTable("AccessApiKeys", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("CompatJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Position");

                    b.HasIndex("OwnerUserId", "Priority", "Position");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ChannelModelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModelInfoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("PricingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PricingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsImage")
                        .HasColumnType("boolean");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("UpstreamModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("ModelInfoId");

                    b.HasIndex("PricingPlanId");

                    b.HasIndex("ChannelId", "Position");

                    b.HasIndex("ChannelId", "RequestModel");

                    b.ToTable("ChannelModelMappings", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CatalogJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Enabled");

                    b.HasIndex("MatchPattern");

                    b.HasIndex("MatchType");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Scope", "ChannelId", "ModelKey");

                    b.HasIndex("Scope", "ProviderId", "ModelKey");

                    b.ToTable("ModelInfos", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CachedInputPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<double>("InputPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OutputPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("MatchPattern");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.HasIndex("Vendor");

                    b.ToTable("ModelPricings", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelPricingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModelInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Enabled");

                    b.HasIndex("ModelInfoId");

                    b.ToTable("ModelPricingPlans", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelPricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TiersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("BillingItem");

                    b.HasIndex("Enabled");

                    b.HasIndex("PricingPlanId");

                    b.ToTable("ModelPricingRules", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.ModelProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Enabled");

                    b.HasIndex("SortOrder");

                    b.ToTable("ModelProviders", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<int>("CacheReadTokens")
                        .HasColumnType("integer");

                    b.Property<int>("CacheWriteTokens")
                        .HasColumnType("integer");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text");

                    b.Property<double?>("CompletedAt")
                        .HasColumnType("double precision");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStream")
                        .HasColumnType("boolean");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentRequestLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid?>("PricingModelInfoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PricingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("PricingSnapshotJson")
                        .HasColumnType("text");

                    b.Property<double?>("ProcessingStartedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int?>("TtftMs")
                        .HasColumnType("integer");

                    b.Property<string>("UpstreamModel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LifecycleStatus");

                    b.HasIndex("Model");

                    b.HasIndex("ParentRequestLogId");

                    b.HasIndex("Path");

                    b.HasIndex("PricingModelInfoId");

                    b.HasIndex("PricingPlanId");

                    b.HasIndex("RequestType");

                    b.HasIndex("StatusCode");

                    b.HasIndex("UpstreamModel");

                    b.HasIndex("OwnerUserId", "Id");

                    b.ToTable("RequestLogs", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLogDetail", b =>
                {
                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("OcrJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<string>("StreamTimingsJson")
                        .HasColumnType("text");

                    b.Property<string>("UpstreamRequestBody")
                        .HasColumnType("text");

                    b.Property<string>("UpstreamResponseBody")
                        .HasColumnType("text");

                    b.Property<string>("WebSearchJson")
                        .HasColumnType("text");

                    b.HasKey("RequestLogId");

                    b.ToTable("RequestLogDetails", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.RequestLogStreamLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("OccurredAt")
                        .HasColumnType("double precision");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RequestLogId", "Sequence")
                        .IsUnique();

                    b.ToTable("RequestLogStreamLines", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.TavilyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.ToTable("TavilyKeys", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenCodex.Core.Domain.WebSearchSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CreatedAt")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("KeyUsageLimit")
                        .HasColumnType("integer");

                    b.Property<double>("UpdatedAt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WebSearchSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
